version: 2.1

executors:
  node-executor:
    machine:
      image: ubuntu-2204:2022.10.2

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: checkout and install sbt
          command: |
            sudo apt-get update
            sudo apt-get install apt-transport-https curl gnupg -yqq
            echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | sudo tee /etc/apt/sources.list.d/sbt.list
            echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | sudo tee /etc/apt/sources.list.d/sbt_old.list
            curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo -H gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/scalasbt-release.gpg --import
            sudo chmod 644 /etc/apt/trusted.gpg.d/scalasbt-release.gpg
            sudo apt-get update
            sudo apt-get install sbt
            sudo apt-get install openjdk-11-jdk
            ls /usr/lib/jvm/
            echo $JAVA_HOME
            echo $PATH
            which java
      - run:
          name: compile
          environment:
            JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
          command: |
            echo $JAVA_HOME
            which java
            java --version

  test:
    executor: node-executor
    steps:
      - run:
          name: tests
          command: "sbt test"
      - run:
          command: "mkdir /tmp/scalatests"
      - run:
          command: >
            find target/test-reports -type f -exec cp {} /tmp/scalatests/ \;
      - store_test_results:
          path: /tmp/scalatests
      - store_artifacts:
          path: /tmp/scalatests
          destination: scalatests
  package:
    executor: node-executor
    steps:
      - run:
          name: create package
          command: "sbt package"

workflows:
  version: 2
  ci:
    jobs:
      - build
      #- test:
      #    requires:
      #      - build
      #- package:
      #    requires:
      #      - test

